source:
  adapter: sqlserver
  dsn: sqlexpress
  mode: odbc
  database: omei

target:
  adapter: mysql2
  database: t-web
  encoding: utf8
  timeout: 5000
  username: root
  password: 
  host: localhost



