source:
  adapter: sqlserver
  dsn: OmeiOdbc
  host: localhost\\sqlexpress
  database: travel
  username: travel
  password: travel

target:
  adapter: mysql
  database: travel
  encoding: utf8
  timeout: 5000
  username: travel
  password: travel
  host: localhost



