source:
  adapter: sqlite3
  database: ../data/omei.sqlite

target:
  adapter: sqlite3
  database: /home/jimmy/work/omei/db/dev.sqlite3

infos:
  adapter: sqlite3
  database: /home/jimmy/work/omei/db/infos.sqlite3

operates:
  adapter: sqlite3
  database: /home/jimmy/work/omei/db/operates.sqlite3
  